### ISSUE TITLE
Revisar a primeira versão da Cartilha em markdown, para verificar se está no formato correto. Usar como guia e consulta: https://guides.github.com/features/mastering-markdown/

### ISSUE THREAD

**Issue by christinaflach** [christinaflach/Cartilha-Computacao-UFBA#14]
Até 11/5/2018.

**Comment by christinaflach** [comment]
Em dupla. Escolher um arquivo na lista abaixo, marcar e comentar aqui na issue, registrando sua escolha. Revisar, comparando com o texto em https://drive.google.com/file/d/14WUBWbpufgcqZCKLTJzW080Kg2R9cgiz/view?usp=sharing 
Quando terminar de revisar, comentar novamente, e indicar os nomes que compõem a dupla.

- [x] markdown/assistencia.md
- [x] markdown/atividades.md
- [x] markdown/avaliacoes.md
- [x] markdown/bcc.md
- [ ] markdown/copyright.md
- [x] markdown/cultura.md
- [ ] markdown/curriculum-Copia.md
- [ ] markdown/curriculum.md
- [x] markdown/departamento.md
- [x] markdown/direitos.md
- [ ] markdown/ensino.md
- [x] markdown/extensao.md
- [x] markdown/glossario.md
- [x] markdown/historico.md
- [ ] markdown/historico.tex.md
- [x] markdown/honra.md
- [ ] markdown/introducao.md
- [ ] markdown/lcc.md
- [ ] markdown/pgcomp.md
- [x] markdown/representacao.md
- [x] markdown/siglas1.md
- [x] markdown/siglas2.md
- [ ] markdown/solicitacoes.md

**Comment by fernando-lacerda** [comment]
**/markdown/solicitacoes.md**

**Comment by fernando-lacerda** [comment]
Fernando Lacerda:
/markdown/solicitacoes.md

**Comment by ab-vitor** [comment]
Vítor Alves Barbosa e Pablo Henrique Rego dos Santos Cabral:
/markdown/honra.md

**Comment by GisellyAR** [comment]
markdown/cultura.md

**Comment by christinaflach** [comment]
Lembrete: terminar a revisão até o final do dia 12/5, sábado.

**Comment by AlbertoLucass** [comment]
Alberto Lucas e Roque Mateus 
markdown/siglas2.md

**Comment by GWbushin** [comment]
George Gonçalves
markdown/atividades.md

**Comment by GWbushin** [comment]
George Gonçalves
Olá! Revisei o arquivo: markdown/atividades.md. 
Adicionei imagens e uma parte de texto que faltava, porém me surgiu uma dúvida sobre como colocar imagens do lado de parágrafos e não consegui encontrar nada a respeito. Alguém sabe como fazer?

**Comment by Murilove** [comment]
Murilo Vicente Ferreira da Silva Souza e Jardel Pereira Baia Junior
Arquivo "markdown/representação.md" revisado.

**Comment by SamuelRios** [comment]
Samuel Rios e Alan Divino
Arquivo "markdown/siglas1.md"

**Comment by vinicius1999** [comment]
VinÍcius Mandinho e Gabriel Baptista
markdown/assistencia.md

**Comment by GisellyAR** [comment]
Giselly Alves e Flávio Nascimento 
markdown/cultura.md

**Comment by Saikys** [comment]
Matheus Rheinschmitt
markdown/avaliacoes.md

**Comment by queilahabreu** [comment]
Queila Abreu e Laila Mota 
markdown/extensao.md

**Comment by viniciusth** [comment]
Vinicius Teixeira
markdown/introducao.md

**Comment by furran** [comment]
Francisco Montenegro
markdown/direitos.md

**Comment by Saikys** [comment]
Matheus Rheinschmitt
markdown/avaliacoes.md

**Comment by andreluizsgf** [comment]
André Luiz dos Santos Gomes Filho
markdown/bcc.md

**Comment by van2509** [comment]
Vandilson Brito e Lucas
Markdown/Departamento.md

**Comment by EduardoIkeda** [comment]
Eduardo Ikeda
markdown/glossario.md

**Comment by pedroww** [comment]
Bruno Nunes e Pedro Pimentel
markdown/historico.md
