### ISSUE TITLE
Revisar a estrutura e o conteúdo da Cartilha, apontando  pontos a melhorar;  trazer uma proposta de evolução da Cartilha.

### ISSUE THREAD

**Issue by christinaflach** [christinaflach/Cartilha-Computacao-UFBA#18]
Para 14/5. 
Em equipe de até 5 pessoas.

**Comment by GisellyAR** [comment]
Certo

Enviado pelo meu Windows Phone
________________________________
De: Christina von Flach<mailto:notifications@github.com>
Enviada em: ‎21/‎05/‎2018 16:26
Para: christinaflach/Cartilha-Computacao-UFBA<mailto:Cartilha-Computacao-UFBA@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Assunto: [christinaflach/Cartilha-Computacao-UFBA] Revisar a estrutura e o conteúdo da Cartilha, apontando pontos a melhorar; trazer uma proposta de evolução da Cartilha. (#18)


Para 14/5.
Em equipe de até 5 pessoas.

**Comment by christinaflach** [comment]
LOG parcial até 17 de maio.

commit 85f1a382e63f833885dd15cfa2090ec1fe28c7b2
Author: lailamt <17855701+lailamt@users.noreply.github.com>
Date:   Thu May 17 02:42:05 2018 -0300

    Update lcc.md

commit a3824863305ade4482ea3d9e7d385740e6a669ae
Author: unixpod <38276514+unixpod@users.noreply.github.com>
Date:   Tue May 15 20:27:42 2018 -0300

    Update departamento.md

commit ed9d3956e872904d74ecef573488384aabba49b5
Author: EduardoIkeda <38788686+EduardoIkeda@users.noreply.github.com>
Date:   Mon May 14 12:39:46 2018 -0300

    Revisao glossario.md

commit 42b09b5cfa4223f76faaabc8f0a2ee2fcf5069b9
Author: Vandilson <38678170+van2509@users.noreply.github.com>
Date:   Sat May 12 22:14:43 2018 -0300

    Add files via upload

commit 984902dd978ffa8002c311fb907e2259b5475a61
Author: Francisco Montenegro Lopes Machado <38672744+Quot3@users.noreply.github.com>
Date:   Sat May 12 14:34:02 2018 -0300

    Update direitos.md

    correção na posição das imagens

commit 925305ec9a31a232851aeb102afda4950d394d91
Author: Francisco Montenegro Lopes Machado <38672744+Quot3@users.noreply.github.com>
Date:   Sat May 12 14:18:48 2018 -0300

    Update direitos.md

commit 1fa727428fb1375b9bcf7a648f1f7d66d5c3cbc7
Author: Saikys <vivibarroscoder@gmail.com>
Date:   Fri May 11 21:00:15 2018 -0300

    avaliacoes.md

    Matheus Rheinschmitt

commit d7808385111df0c36eaf4889168acce64635bc67
Author: Saikys <vivibarroscoder@gmail.com>
Date:   Fri May 11 20:43:11 2018 -0300

    Revisando arquivo avaliacoes.md

    Matheus Rheinschmitt

commit 51a0ebf8f707bbcc7a0f7ab21d81e28b14e90f14
Author: MrAlves17 <38429470+MrAlves17@users.noreply.github.com>
Date:   Fri May 11 16:59:16 2018 -0300

    Rápida revisão extra

commit 2dbdad1dd5c4fb11fcc3bc49912d2c2363963575
Author: MrAlves17 <38429470+MrAlves17@users.noreply.github.com>
Date:   Fri May 11 16:57:29 2018 -0300

    Revisão

    Coloquei apenas uma quebra de linha em cada parágrafo.

commit 9269bdfdea62d4c840e8332b8fb7afc79fb4a240
Author: GWbushin <38930013+GWbushin@users.noreply.github.com>
Date:   Fri May 11 14:23:04 2018 -0300

    Update atividades.md

commit f1d0d383549bbb1a0a7119934413af89b5c5fe05
Author: Pablo Henrique <pablohenrique.r.c@gmail.com>
Date:   Fri May 11 13:52:35 2018 -0300

    Adicionando revisão parcial do arquivo honra.md

commit f59af35ee27238e9f6c35406198aab7a9a8b36bb
Author: GWbushin <38930013+GWbushin@users.noreply.github.com>
Date:   Fri May 11 09:17:14 2018 -0300

    Update atividades.md

commit ad2f2d5d7cc3c5d007ddf77bf3b27c2781789121
Author: GWbushin <38930013+GWbushin@users.noreply.github.com>
Date:   Fri May 11 08:25:27 2018 -0300

    Update atividades.md

ETC. Para ver contribuições, "git log" !!
