### ISSUE TITLE
Consultar outros estudantes do BCC; trazer uma proposta de evolução da Cartilha.

### ISSUE THREAD

**Issue by christinaflach** [christinaflach/Cartilha-Computacao-UFBA#19]
Ver https://github.com/christinaflach/Cartilha-Computacao-UFBA/blob/mata39-20181/README.md

**Comment by christinaflach** [comment]
Por favor, atualizem progresso do trabalho, usando o próprio github.

**Comment by GWbushin** [comment]
Olá professora e colegas! Bom dia! Queria saber se existe alguma equipe com alguma vaga, pois estou sem equipe ainda. Fico no aguardo.
